// Auto-generated by obfuscate_audio.py. Do not edit manually.
const BOOKS_DATA = [
  {
    "id": 1,
    "title": "The Hitchhiker's Guide to the Galaxy",
    "folder": "book_1",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_1/audios/00_uun5bs9tf6"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_1/audios/01_q7hq1haspy"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_1/audios/02_1z072u3im1"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_1/audios/03_rhtd47ovpt"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_1/audios/04_0g1pdwko88"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_1/audios/05_zgesmc1kgp"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_1/audios/06_ypb8ysu883"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_1/audios/07_va8nxxwmeu"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_1/audios/08_q6404n7esx"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_1/audios/09_gzsya2cxbd"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_1/audios/10_0n33mhbe11"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_1/audios/11_5wfv8vyfrt"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_1/audios/12_6pn1kw0dnf"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_1/audios/13_7v74z3zw96"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_1/audios/14_muxky9weh0"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_1/audios/15_yvrvpjgs44"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_1/audios/16_voez9akcbk"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_1/audios/17_za0wcdzri3"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_1/audios/18_z56bc4vmic"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_1/audios/19_aoy9v2fr1n"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_1/audios/20_23rea69nd2"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_1/audios/21_v7ppdrhjt6"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_1/audios/22_qjyxbmta0s"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_1/audios/23_v2sov2wqqx"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_1/audios/24_vasfcst6v3"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_1/audios/25_tev1hq811y"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_1/audios/26_jib69x7fjb"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_1/audios/27_dhen1buuzy"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_1/audios/28_uxr0c8j74p"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_1/audios/29_ihyk1f5viu"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_1/audios/30_7d7xzg4om8"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_1/audios/31_ycy44gbqk7"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_1/audios/32_wziw3kw881"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_1/audios/33_l89ueqkj1z"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_1/audios/34_n42kctq9pw"
      },
      {
        "number": 35,
        "name": "Chapter 35",
        "src": "book_1/audios/35_cis7ad50hm"
      }
    ]
  },
  {
    "id": 2,
    "title": "The Restaurant at the End of the Universe",
    "folder": "book_2",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_2/audios/00_ewdwfis7oy"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_2/audios/01_sam1k5q3y4"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_2/audios/02_4htkrf8wkl"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_2/audios/03_jqn29easo2"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_2/audios/04_5ct50nhqa9"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_2/audios/05_7o6kxnvzzs"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_2/audios/06_87yzl3v77p"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_2/audios/07_8qcihurpj7"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_2/audios/08_9z7vxl6q8o"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_2/audios/09_z991hwhkdp"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_2/audios/10_coqjbh181u"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_2/audios/11_385ndv1xry"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_2/audios/12_eczkgqcish"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_2/audios/13_kw5zj6w82t"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_2/audios/14_lnxfdfjup2"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_2/audios/15_57usyzmogn"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_2/audios/16_x1axz4ui0f"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_2/audios/17_ecerx29pnz"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_2/audios/18_igmvotqsrm"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_2/audios/19_nuf7d9rtbf"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_2/audios/20_9lyx7f2vdh"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_2/audios/21_2qjxigjo1t"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_2/audios/22_0j2he0zmrj"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_2/audios/23_eyax2q0n3m"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_2/audios/24_lfeub1n4xd"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_2/audios/25_kh9fg2pxrq"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_2/audios/26_wagkxb1duz"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_2/audios/27_wvdufm9eqr"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_2/audios/28_lzj2zn5hsn"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_2/audios/29_0711f74fbg"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_2/audios/30_ealsp2fumo"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_2/audios/31_vkn5wdvjmr"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_2/audios/32_ckc53vz0un"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_2/audios/33_9w0ywz76bx"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_2/audios/34_j7l8ne2hrs"
      }
    ]
  },
  {
    "id": 3,
    "title": "Life, the Universe and Everything",
    "folder": "book_3",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_3/audios/00_jvs0hh86wu"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_3/audios/01_2yzbnp4c9s"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_3/audios/02_oms5kdg4qv"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_3/audios/03_35sdrka4g7"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_3/audios/04_29fb1tm8un"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_3/audios/05_59jykh9zt4"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_3/audios/06_xzgkkj3hsa"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_3/audios/07_96ozmq5dfa"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_3/audios/08_osrzs3688u"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_3/audios/09_40v558tk4k"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_3/audios/10_0m06agxt89"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_3/audios/11_6zzstmmu26"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_3/audios/12_3n6dn6emik"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_3/audios/13_auu4tdlk8f"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_3/audios/14_14w5t0ongo"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_3/audios/15_gq14heun3e"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_3/audios/16_mtcp0bfiya"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_3/audios/17_bmxe9iznbv"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_3/audios/18_jurm0gg1n2"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_3/audios/19_swhhkn1kal"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_3/audios/20_rxkn0t202k"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_3/audios/21_i0997psd4a"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_3/audios/22_adh05xmckz"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_3/audios/23_ldwlwk3ij2"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_3/audios/24_5ktu7wvqx0"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_3/audios/25_j44du489te"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_3/audios/26_ock2i9bkpn"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_3/audios/27_8ildo68d3z"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_3/audios/28_xhjajzhaln"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_3/audios/29_mh697koivo"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_3/audios/30_bpjq0zr3sn"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_3/audios/31_7gbups011d"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_3/audios/32_in1xblno9v"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_3/audios/33_vos12iu7xb"
      }
    ]
  },
  {
    "id": 4,
    "title": "So Long, and Thanks for All the Fish",
    "folder": "book_4",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_4/audios/00_xzqriy4i4u"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_4/audios/01_eybxawkcrx"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_4/audios/02_uivom5vv6m"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_4/audios/03_ptlfqkyzah"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_4/audios/04_swf46xjblw"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_4/audios/05_sg872wqo1i"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_4/audios/06_ou9bnm6kgb"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_4/audios/07_c2dx2zjyza"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_4/audios/08_zxx9wh6fuq"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_4/audios/09_sl3han649o"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_4/audios/10_565zyr6ksh"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_4/audios/11_j5rre6k56m"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_4/audios/12_6mrupixnbi"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_4/audios/13_j1ahf86p4i"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_4/audios/14_04tuhsiet6"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_4/audios/15_w27vuga8k7"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_4/audios/16_4oezfdmfvl"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_4/audios/17_lilgmdwqbk"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_4/audios/18_o7aaklwwvb"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_4/audios/19_lc7004ii5w"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_4/audios/20_dtapc8i8x8"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_4/audios/21_a6l3h5p6af"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_4/audios/22_e5s064ryqv"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_4/audios/23_3zqmaibz6t"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_4/audios/24_7zyv75gdsi"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_4/audios/25_oy8amtdwhk"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_4/audios/26_mohqk17p5c"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_4/audios/27_tt4l7zrx02"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_4/audios/28_9tv41gh70a"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_4/audios/29_x4vnzw154d"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_4/audios/30_3mi6m90awt"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_4/audios/31_igqjky2dhv"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_4/audios/32_t8m5emsvt8"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_4/audios/33_b8x436km9y"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_4/audios/34_em9s8c6a90"
      },
      {
        "number": 35,
        "name": "Chapter 35",
        "src": "book_4/audios/35_8bvmi5dwur"
      },
      {
        "number": 36,
        "name": "Chapter 36",
        "src": "book_4/audios/36_bxt6f7v003"
      },
      {
        "number": 37,
        "name": "Chapter 37",
        "src": "book_4/audios/37_z7sccgbhai"
      },
      {
        "number": 38,
        "name": "Chapter 38",
        "src": "book_4/audios/38_9cfxicqm61"
      },
      {
        "number": 39,
        "name": "Chapter 39",
        "src": "book_4/audios/39_kws0hps3jo"
      },
      {
        "number": 40,
        "name": "Chapter 40",
        "src": "book_4/audios/40_y9m280quh8"
      }
    ]
  },
  {
    "id": 5,
    "title": "Mostly Harmless",
    "folder": "book_5",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_5/audios/00_asypk0tk1g"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_5/audios/01_g2i6mik2m1"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_5/audios/02_74wv6asup9"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_5/audios/03_ih5lvbygn7"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_5/audios/04_5pvixdqvcs"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_5/audios/06_z7w82v46q6"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_5/audios/07_fgnagjnit5"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_5/audios/10_81oj0zldf2"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_5/audios/11_wqw0q50kex"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_5/audios/13_09ejnwcrjm"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_5/audios/16_j1uw8mcw39"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_5/audios/17_hnuair4s4b"
      }
    ]
  },
  {
    "id": 6,
    "title": "And Another Thing...",
    "folder": "book_6",
    "chapters": []
  }
];
