// Auto-generated by obfuscate_audio.py. Do not edit manually.
const BOOKS_DATA = [
  {
    "id": 1,
    "title": "The Hitchhiker's Guide to the Galaxy",
    "folder": "book_1",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_1/audios/00_6n6evpc3yt"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_1/audios/01_0z5vi27mwm"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_1/audios/02_d32vkhhcqt"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_1/audios/03_bgtnes0tyl"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_1/audios/04_34i182ofw1"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_1/audios/05_qhvmbxd83l"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_1/audios/06_c2mzf2nijb"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_1/audios/07_8veqcs21ly"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_1/audios/08_k9ygrlrlzm"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_1/audios/09_8t4sfsjqkw"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_1/audios/10_jz54chobhb"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_1/audios/11_gtluq4addi"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_1/audios/12_p3dum2n8fm"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_1/audios/13_mqahp35nqd"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_1/audios/14_g55j79ad7t"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_1/audios/15_sfkpsouk56"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_1/audios/16_4stb8tmd88"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_1/audios/17_pprvxw50ew"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_1/audios/18_q8lhrzrfca"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_1/audios/19_xhmolc9jwe"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_1/audios/20_7bkh46qbho"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_1/audios/21_ltwe1ni3jp"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_1/audios/22_1qrygd3yw8"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_1/audios/23_a5jmgmyjog"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_1/audios/24_leiz83yh75"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_1/audios/25_flojyhvpt5"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_1/audios/26_6epf8d3llk"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_1/audios/27_1bqpgkq9tg"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_1/audios/28_cml1gy98rz"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_1/audios/29_u6e2zdfjwo"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_1/audios/30_si0tf4v9zd"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_1/audios/31_94y214677i"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_1/audios/32_pl3vk4xyls"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_1/audios/33_pt04ecvm1k"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_1/audios/34_hf5mk6sko5"
      },
      {
        "number": 35,
        "name": "Chapter 35",
        "src": "book_1/audios/35_me3e6a1itm"
      }
    ]
  },
  {
    "id": 2,
    "title": "The Restaurant at the End of the Universe",
    "folder": "book_2",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_2/audios/00_01cq68w3hg"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_2/audios/01_x07p37552b"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_2/audios/02_8f1ji4ktq6"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_2/audios/03_nbqoqq0v1h"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_2/audios/04_ybgvb1nqnl"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_2/audios/05_uhk58osrel"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_2/audios/06_av5a99ct7t"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_2/audios/07_c84kdkdc85"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_2/audios/08_s9x062vjpa"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_2/audios/09_wqoc2nfkob"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_2/audios/10_3gpqbb5opr"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_2/audios/11_dbw9jys475"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_2/audios/12_0qw44ae4en"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_2/audios/13_e5uqqq1vnf"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_2/audios/14_mub4k8xvsx"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_2/audios/15_p6gu7rbth7"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_2/audios/16_d7oo3qfc8g"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_2/audios/17_w13ixkrh8j"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_2/audios/18_2bx2lxl791"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_2/audios/19_pjavidyi6k"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_2/audios/20_i0647llnvy"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_2/audios/21_eir9h7v2u7"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_2/audios/22_jnycnmzmtj"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_2/audios/23_b25ahddtqj"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_2/audios/24_5w3j2pd924"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_2/audios/25_bmhmxy25sl"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_2/audios/26_xuzb748tri"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_2/audios/27_9gmk3htug1"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_2/audios/28_q5qly89eg6"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_2/audios/29_366tq3s336"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_2/audios/30_392345bewv"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_2/audios/31_nh4l4m6lja"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_2/audios/32_5pi4fejlm1"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_2/audios/33_j0p98npvgl"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_2/audios/34_oa44cbblr9"
      }
    ]
  },
  {
    "id": 3,
    "title": "Life, the Universe and Everything",
    "folder": "book_3",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_3/audios/00_cc3dgbbr0p"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_3/audios/01_8mjq5yvavb"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_3/audios/02_hhqyb1rbu3"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_3/audios/03_ahqiver9bv"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_3/audios/04_xcnpzya52x"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_3/audios/05_vo0my0n5yz"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_3/audios/06_glzrf4wni2"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_3/audios/07_cjg8w9femj"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_3/audios/08_wk6o3jdh9e"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_3/audios/09_aso6px4u88"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_3/audios/10_qkayjzp57b"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_3/audios/11_6tzst4d2xk"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_3/audios/12_o0follra4s"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_3/audios/13_wcfho8dul6"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_3/audios/14_931v7vyqzc"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_3/audios/15_1i38977m6f"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_3/audios/16_xy63ygagq1"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_3/audios/17_pshwrwfoa3"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_3/audios/18_p8pr9xn355"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_3/audios/19_shen23b06y"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_3/audios/20_yrby2zyh9v"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_3/audios/21_2a53wf5m3b"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_3/audios/22_4k7zzskw54"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_3/audios/23_1hbwy2ro2t"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_3/audios/24_cxwdpty30y"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_3/audios/25_w8lr11j40j"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_3/audios/26_r1i3gilfup"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_3/audios/27_oehxej8ypy"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_3/audios/28_j50ypepna7"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_3/audios/29_qkx7hkvf52"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_3/audios/30_bxxg5gqaqo"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_3/audios/31_a7j5xotor7"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_3/audios/32_hmgakkgf3y"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_3/audios/33_c33w15w67g"
      }
    ]
  },
  {
    "id": 4,
    "title": "So Long, and Thanks for All the Fish",
    "folder": "book_4",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_4/audios/00_22a4872xna"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_4/audios/01_jodcol09r7"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_4/audios/02_4gg2yrcj56"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_4/audios/03_5zsyrx99lb"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_4/audios/04_9d7p7ib74z"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_4/audios/05_x1wgarkr4q"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_4/audios/06_xii5v10a5s"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_4/audios/07_epbvv2lq83"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_4/audios/08_1uqtxwfq4u"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_4/audios/09_hxr0gi55pj"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_4/audios/10_46fokzxgse"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_4/audios/11_oj11wrx1vh"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_4/audios/12_8cnocdywfe"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_4/audios/13_7terf8rit6"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_4/audios/14_ijlupz6qog"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_4/audios/15_169redrwx9"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_4/audios/16_65rmizmcb7"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_4/audios/17_ituiet9v5s"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_4/audios/18_v84xhqlnig"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_4/audios/19_6s1kzris0l"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_4/audios/20_ttybe7wgju"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_4/audios/21_08kjrv0w19"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_4/audios/22_7fzzcb88qx"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_4/audios/23_q53vr3iy22"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_4/audios/24_9xefxihber"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_4/audios/25_pueuecfrrh"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_4/audios/26_75thqomx6d"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_4/audios/27_eubriem992"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_4/audios/28_ktny56jl0y"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_4/audios/29_8yyjopa1b4"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_4/audios/30_ogwor4qlpt"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_4/audios/31_8txssvfemv"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_4/audios/32_2c31r336mm"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_4/audios/33_0nuw0mbv15"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_4/audios/34_jyzytw3jis"
      },
      {
        "number": 35,
        "name": "Chapter 35",
        "src": "book_4/audios/35_hcdxsugj4d"
      },
      {
        "number": 36,
        "name": "Chapter 36",
        "src": "book_4/audios/36_heuixnklt0"
      },
      {
        "number": 37,
        "name": "Chapter 37",
        "src": "book_4/audios/37_a66o5nrxui"
      },
      {
        "number": 38,
        "name": "Chapter 38",
        "src": "book_4/audios/38_ks4icleb5b"
      },
      {
        "number": 39,
        "name": "Chapter 39",
        "src": "book_4/audios/39_xlz9twzg3s"
      },
      {
        "number": 40,
        "name": "Chapter 40",
        "src": "book_4/audios/40_d1au1xgf1m"
      }
    ]
  },
  {
    "id": 5,
    "title": "Mostly Harmless",
    "folder": "book_5",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_5/audios/00_avml750700"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_5/audios/01_bkyb4yoic0"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_5/audios/02_axdw8zwyjj"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_5/audios/03_ih4f9gz98t"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_5/audios/04_o0140qlunf"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_5/audios/05_5s8iy5ta2h"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_5/audios/06_d1xm8w47qr"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_5/audios/07_6f08v9s4vl"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_5/audios/10_a98dhu5nra"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_5/audios/11_6237nndbto"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_5/audios/13_lk9sw2fwmb"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_5/audios/16_9wbnkk1507"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_5/audios/17_7eu6pdb3it"
      }
    ]
  },
  {
    "id": 6,
    "title": "And Another Thing...",
    "folder": "book_6",
    "chapters": []
  }
];
