// Auto-generated by generate_metadata.py. Do not edit manually.
const BOOKS_DATA = [
  {
    "id": 1,
    "title": "The Hitchhiker's Guide to the Galaxy",
    "folder": "book_1",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_1/audios/chapter_0.mp3"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_1/audios/chapter_1.mp3"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_1/audios/chapter_2.mp3"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_1/audios/chapter_3.mp3"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_1/audios/chapter_4.mp3"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_1/audios/chapter_5.mp3"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_1/audios/chapter_6.mp3"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_1/audios/chapter_7.mp3"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_1/audios/chapter_8.mp3"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_1/audios/chapter_9.mp3"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_1/audios/chapter_10.mp3"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_1/audios/chapter_11.mp3"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_1/audios/chapter_12.mp3"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_1/audios/chapter_13.mp3"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_1/audios/chapter_14.mp3"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_1/audios/chapter_15.mp3"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_1/audios/chapter_16.mp3"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_1/audios/chapter_17.mp3"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_1/audios/chapter_18.mp3"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_1/audios/chapter_19.mp3"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_1/audios/chapter_20.mp3"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_1/audios/chapter_21.mp3"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_1/audios/chapter_22.mp3"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_1/audios/chapter_23.mp3"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_1/audios/chapter_24.mp3"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_1/audios/chapter_25.mp3"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_1/audios/chapter_26.mp3"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_1/audios/chapter_27.mp3"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_1/audios/chapter_28.mp3"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_1/audios/chapter_29.mp3"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_1/audios/chapter_30.mp3"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_1/audios/chapter_31.mp3"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_1/audios/chapter_32.mp3"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_1/audios/chapter_33.mp3"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_1/audios/chapter_34.mp3"
      },
      {
        "number": 35,
        "name": "Chapter 35",
        "src": "book_1/audios/chapter_35.mp3"
      }
    ]
  },
  {
    "id": 2,
    "title": "The Restaurant at the End of the Universe",
    "folder": "book_2",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_2/audios/chapter_0.mp3"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_2/audios/chapter_1.mp3"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_2/audios/chapter_2.mp3"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_2/audios/chapter_3.mp3"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_2/audios/chapter_4.mp3"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_2/audios/chapter_5.mp3"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_2/audios/chapter_6.mp3"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_2/audios/chapter_7.mp3"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_2/audios/chapter_8.mp3"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_2/audios/chapter_9.mp3"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_2/audios/chapter_10.mp3"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_2/audios/chapter_11.mp3"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_2/audios/chapter_12.mp3"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_2/audios/chapter_13.mp3"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_2/audios/chapter_14.mp3"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_2/audios/chapter_15.mp3"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_2/audios/chapter_16.mp3"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_2/audios/chapter_17.mp3"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_2/audios/chapter_18.mp3"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_2/audios/chapter_19.mp3"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_2/audios/chapter_20.mp3"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_2/audios/chapter_21.mp3"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_2/audios/chapter_22.mp3"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_2/audios/chapter_23.mp3"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_2/audios/chapter_24.mp3"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_2/audios/chapter_25.mp3"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_2/audios/chapter_26.mp3"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_2/audios/chapter_27.mp3"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_2/audios/chapter_28.mp3"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_2/audios/chapter_29.mp3"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_2/audios/chapter_30.mp3"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_2/audios/chapter_31.mp3"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_2/audios/chapter_32.mp3"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_2/audios/chapter_33.mp3"
      },
      {
        "number": 34,
        "name": "Chapter 34",
        "src": "book_2/audios/chapter_34.mp3"
      }
    ]
  },
  {
    "id": 3,
    "title": "Life, the Universe and Everything",
    "folder": "book_3",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_3/audios/chapter_0.mp3"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_3/audios/chapter_1.mp3"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_3/audios/chapter_2.mp3"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_3/audios/chapter_3.mp3"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_3/audios/chapter_4.mp3"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_3/audios/chapter_5.mp3"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_3/audios/chapter_6.mp3"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_3/audios/chapter_7.mp3"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_3/audios/chapter_8.mp3"
      },
      {
        "number": 9,
        "name": "Chapter 9",
        "src": "book_3/audios/chapter_9.mp3"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_3/audios/chapter_10.mp3"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_3/audios/chapter_11.mp3"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_3/audios/chapter_12.mp3"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_3/audios/chapter_13.mp3"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_3/audios/chapter_14.mp3"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_3/audios/chapter_15.mp3"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_3/audios/chapter_16.mp3"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_3/audios/chapter_17.mp3"
      },
      {
        "number": 18,
        "name": "Chapter 18",
        "src": "book_3/audios/chapter_18.mp3"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_3/audios/chapter_19.mp3"
      },
      {
        "number": 20,
        "name": "Chapter 20",
        "src": "book_3/audios/chapter_20.mp3"
      },
      {
        "number": 21,
        "name": "Chapter 21",
        "src": "book_3/audios/chapter_21.mp3"
      },
      {
        "number": 22,
        "name": "Chapter 22",
        "src": "book_3/audios/chapter_22.mp3"
      },
      {
        "number": 23,
        "name": "Chapter 23",
        "src": "book_3/audios/chapter_23.mp3"
      },
      {
        "number": 24,
        "name": "Chapter 24",
        "src": "book_3/audios/chapter_24.mp3"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_3/audios/chapter_25.mp3"
      },
      {
        "number": 26,
        "name": "Chapter 26",
        "src": "book_3/audios/chapter_26.mp3"
      },
      {
        "number": 27,
        "name": "Chapter 27",
        "src": "book_3/audios/chapter_27.mp3"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_3/audios/chapter_28.mp3"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_3/audios/chapter_29.mp3"
      },
      {
        "number": 30,
        "name": "Chapter 30",
        "src": "book_3/audios/chapter_30.mp3"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_3/audios/chapter_31.mp3"
      },
      {
        "number": 32,
        "name": "Chapter 32",
        "src": "book_3/audios/chapter_32.mp3"
      },
      {
        "number": 33,
        "name": "Chapter 33",
        "src": "book_3/audios/chapter_33.mp3"
      }
    ]
  },
  {
    "id": 4,
    "title": "So Long, and Thanks for All the Fish",
    "folder": "book_4",
    "chapters": [
      {
        "number": 0,
        "name": "Chapter 0",
        "src": "book_4/audios/chapter_0.mp3"
      },
      {
        "number": 1,
        "name": "Chapter 1",
        "src": "book_4/audios/chapter_1.mp3"
      },
      {
        "number": 2,
        "name": "Chapter 2",
        "src": "book_4/audios/chapter_2.mp3"
      },
      {
        "number": 3,
        "name": "Chapter 3",
        "src": "book_4/audios/chapter_3.mp3"
      },
      {
        "number": 4,
        "name": "Chapter 4",
        "src": "book_4/audios/chapter_4.mp3"
      },
      {
        "number": 5,
        "name": "Chapter 5",
        "src": "book_4/audios/chapter_5.mp3"
      },
      {
        "number": 6,
        "name": "Chapter 6",
        "src": "book_4/audios/chapter_6.mp3"
      },
      {
        "number": 7,
        "name": "Chapter 7",
        "src": "book_4/audios/chapter_7.mp3"
      },
      {
        "number": 8,
        "name": "Chapter 8",
        "src": "book_4/audios/chapter_8.mp3"
      },
      {
        "number": 10,
        "name": "Chapter 10",
        "src": "book_4/audios/chapter_10.mp3"
      },
      {
        "number": 11,
        "name": "Chapter 11",
        "src": "book_4/audios/chapter_11.mp3"
      },
      {
        "number": 12,
        "name": "Chapter 12",
        "src": "book_4/audios/chapter_12.mp3"
      },
      {
        "number": 13,
        "name": "Chapter 13",
        "src": "book_4/audios/chapter_13.mp3"
      },
      {
        "number": 14,
        "name": "Chapter 14",
        "src": "book_4/audios/chapter_14.mp3"
      },
      {
        "number": 15,
        "name": "Chapter 15",
        "src": "book_4/audios/chapter_15.mp3"
      },
      {
        "number": 16,
        "name": "Chapter 16",
        "src": "book_4/audios/chapter_16.mp3"
      },
      {
        "number": 17,
        "name": "Chapter 17",
        "src": "book_4/audios/chapter_17.mp3"
      },
      {
        "number": 19,
        "name": "Chapter 19",
        "src": "book_4/audios/chapter_19.mp3"
      },
      {
        "number": 25,
        "name": "Chapter 25",
        "src": "book_4/audios/chapter_25.mp3"
      },
      {
        "number": 28,
        "name": "Chapter 28",
        "src": "book_4/audios/chapter_28.mp3"
      },
      {
        "number": 29,
        "name": "Chapter 29",
        "src": "book_4/audios/chapter_29.mp3"
      },
      {
        "number": 31,
        "name": "Chapter 31",
        "src": "book_4/audios/chapter_31.mp3"
      },
      {
        "number": 38,
        "name": "Chapter 38",
        "src": "book_4/audios/chapter_38.mp3"
      },
      {
        "number": 39,
        "name": "Chapter 39",
        "src": "book_4/audios/chapter_39.mp3"
      },
      {
        "number": 40,
        "name": "Chapter 40",
        "src": "book_4/audios/chapter_40.mp3"
      }
    ]
  },
  {
    "id": 5,
    "title": "Mostly Harmless",
    "folder": "book_5",
    "chapters": []
  },
  {
    "id": 6,
    "title": "And Another Thing...",
    "folder": "book_6",
    "chapters": []
  }
];
