#!/usr/bin/env python3
import os
import re
import json

# Book name mapping
BOOK_NAMES = {
    1: "The Hitchhiker's Guide to the Galaxy",
    2: "The Restaurant at the End of the Universe",
    3: "Life, the Universe and Everything",
    4: "So Long, and Thanks for All the Fish",
    5: "Mostly Harmless",
    6: "And Another Thing..."
}

def scan_books():
    books_data = []
    base_dir = os.path.dirname(os.path.abspath(__file__))
    
    for book_id in range(1, 7):
        book_title = BOOK_NAMES.get(book_id)
        folder_name = f"book_{book_id}"
        audios_dir = os.path.join(base_dir, folder_name, "audios")
        
        chapters = []
        if os.path.isdir(audios_dir):
            # Scan all .mp3 files in the audios folder
            for file_name in os.listdir(audios_dir):
                if file_name.endswith(".mp3"):
                    # Extract chapter number from filename (e.g., chapter_0.mp3 -> 0)
                    match = re.search(r'chapter_(\d+)\.mp3$', file_name)
                    if match:
                        chap_num = int(match.group(1))
                        display_name = f"Chapter {chap_num}"
                        chapters.append({
                            "number": chap_num,
                            "name": display_name,
                            "src": f"{folder_name}/audios/{file_name}"
                        })
                        
        # Sort chapters numerically
        chapters.sort(key=lambda x: x["number"])
        
        books_data.append({
            "id": book_id,
            "title": book_title,
            "folder": folder_name,
            "chapters": chapters
        })
        
    # Write the books data into a JS file
    output_path = os.path.join(base_dir, "books_data.js")
    with open(output_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by generate_metadata.py. Do not edit manually.\n")
        f.write("const BOOKS_DATA = ")
        f.write(json.dumps(books_data, indent=2))
        f.write(";\n")
        
    print(f"Generated metadata for {len(books_data)} books in {output_path}")

if __name__ == "__main__":
    scan_books()
