#!/usr/bin/env python3
import os
import random
import string
import base64
import re
import json

BOOK_NAMES = {
    1: "The Hitchhiker's Guide to the Galaxy",
    2: "The Restaurant at the End of the Universe",
    3: "Life, the Universe and Everything",
    4: "So Long, and Thanks for All the Fish",
    5: "Mostly Harmless",
    6: "And Another Thing..."
}

def generate_random_string(length=12):
    return ''.join(random.choices(string.ascii_lowercase + string.digits, k=length))

def main():
    base_dir = os.path.dirname(os.path.abspath(__file__))
    tts_agent_dir = os.path.abspath(os.path.join(base_dir, "..", "TTS_agent"))
    
    if not os.path.exists(tts_agent_dir):
        print(f"Error: TTS_agent directory not found at {tts_agent_dir}")
        return

    # Generate a random 16-byte key
    key_length = 16
    key = [random.randint(0, 255) for _ in range(key_length)]
    mask = random.randint(1, 254)
    obfuscated_key = [b ^ mask for b in key]
    
    print(f"Generated new encryption key (mask: {mask})")
    
    # Process books
    books_data = []
    for book_id in range(1, 7):
        book_title = BOOK_NAMES.get(book_id)
        folder_name = f"book_{book_id}"
        
        # Source directory for audio files
        src_audios_dir = os.path.join(tts_agent_dir, folder_name, "audios")
        # Destination directory in HGTTG
        dest_audios_dir = os.path.join(base_dir, folder_name, "audios")
        
        # Clean destination directory or ensure it exists
        os.makedirs(dest_audios_dir, exist_ok=True)
        # Remove any existing files in destination directory to prevent orphan audio files
        for f in os.listdir(dest_audios_dir):
            file_path = os.path.join(dest_audios_dir, f)
            if os.path.isfile(file_path):
                os.remove(file_path)
                
        chapters = []
        if os.path.isdir(src_audios_dir):
            # Scan all .mp3 files in the source folder
            for file_name in os.listdir(src_audios_dir):
                if file_name.endswith(".mp3"):
                    # Extract chapter number
                    match = re.search(r'chapter_(\d+)\.mp3$', file_name)
                    if match:
                        chap_num = int(match.group(1))
                        
                        # Read binary data
                        src_file_path = os.path.join(src_audios_dir, file_name)
                        with open(src_file_path, "rb") as f_in:
                            data = f_in.read()
                            
                        # Encrypt with XOR key
                        encrypted_data = bytes(b ^ key[i % len(key)] for i, b in enumerate(data))
                        
                        # Base64 encode
                        encoded_str = base64.b64encode(encrypted_data).decode('utf-8')
                        
                        # Generate random filename starting with formatted chapter number (e.g., 00_abc, 01_def)
                        chap_prefix = f"{chap_num:02d}"
                        rand_name = generate_random_string(10)
                        dest_file_name = f"{chap_prefix}_{rand_name}"
                        dest_file_path = os.path.join(dest_audios_dir, dest_file_name)
                        
                        # Write the base64 encoded string to the destination file
                        with open(dest_file_path, "w", encoding="utf-8") as f_out:
                            f_out.write(encoded_str)
                            
                        display_name = f"Chapter {chap_num}"
                        chapters.append({
                            "number": chap_num,
                            "name": display_name,
                            "src": f"{folder_name}/audios/{dest_file_name}"
                        })
                        
        # Sort chapters numerically
        chapters.sort(key=lambda x: x["number"])
        
        books_data.append({
            "id": book_id,
            "title": book_title,
            "folder": folder_name,
            "chapters": chapters
        })
        
    # Write the books data into books_data.js in the HGTTG folder
    books_data_path = os.path.join(base_dir, "books_data.js")
    with open(books_data_path, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by obfuscate_audio.py. Do not edit manually.\n")
        f.write("const BOOKS_DATA = ")
        f.write(json.dumps(books_data, indent=2))
        f.write(";\n")
    print(f"Generated books_data.js at {books_data_path}")

    # Update index.html with the obfuscated key
    index_html_path = os.path.join(base_dir, "index.html")
    if os.path.exists(index_html_path):
        with open(index_html_path, "r", encoding="utf-8") as f:
            index_content = f.read()
            
        # Regex to replace content between markers
        pattern = r"(\/\/ OBFUSCATED_KEY_START\n)(.*?)(\n\s*\/\/ OBFUSCATED_KEY_END)"
        replacement = f"\\1            const obs = {json.dumps(obfuscated_key)};\n            const mask = {mask};\\3"
        
        new_content, count = re.subn(pattern, replacement, index_content, flags=re.DOTALL)
        if count > 0:
            with open(index_html_path, "w", encoding="utf-8") as f:
                f.write(new_content)
            print("Successfully updated obfuscated key in index.html")
        else:
            print("Warning: Could not find OBFUSCATED_KEY markers in index.html")

if __name__ == "__main__":
    main()
